DROP TABLE IF EXISTS MERCHANT;

CREATE TABLE MERCHANT(
   ID             SERIAL PRIMARY KEY NOT NULL,
   CREATE_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
   NAME           VARCHAR(50),
   LAST_NAME      VARCHAR(50) NOT NULL,
   BIRTH_DATE     DATE
);

DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(
   ID             SERIAL PRIMARY KEY NOT NULL,
   CREATE_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
   LABEL          VARCHAR(250),
   UNIT_PRICE     NUMERIC NOT NULL,
   CURRENCY       VARCHAR(50) NOT NULL,
   WEIGHT         NUMERIC,
   HEIGHT         NUMERIC   
);

DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS(
   ID             SERIAL PRIMARY KEY NOT NULL,
   NUMBER         INT,
   STREET         VARCHAR(250),
   ZIP_CODE       VARCHAR(50),
   MERCHANT_ID    INT,
   CONSTRAINT fk_merchant
      FOREIGN KEY(MERCHANT_ID) 
	  REFERENCES MERCHANT(ID)
);

DROP TABLE IF EXISTS MERCHANT_PRODUCT;

CREATE TABLE MERCHANT_PRODUCT (
  MERCHANT_ID    INT NOT NULL,
  PRODUCT_ID     INT NOT NULL,
  CREATE_DATE    TIMESTAMP WITH TIME ZONE NOT NULL,
  CONSTRAINT pk_merchant_product
	PRIMARY KEY (MERCHANT_ID, PRODUCT_ID),
  CONSTRAINT fk_merchant
	FOREIGN KEY (MERCHANT_ID)
	REFERENCES MERCHANT(ID)
	ON DELETE CASCADE,
  CONSTRAINT fk_product
	FOREIGN KEY (PRODUCT_ID)
	REFERENCES PRODUCT(ID)
	ON DELETE CASCADE
);
